### ISSUE TITLE
registration token がrefreshされる場合の処理

### ISSUE THREAD

**Issue by ncmbsdk** [NIFCLOUD-mbaas/ncmb_android#13]
[What is Instance ID?](https://developers.google.com/instance-id/#instance_id_lifecycle)にて、registration tokenがリフレッシュされる場合について書かれている

> Tokens are unique and secure, but your app or the Instance ID service may need to refresh tokens in the event of a security issue or when a user uninstalls and reinstalls your app during device restoration. Your app must implement a listener to respond to token refresh requests from the Instance ID service.

このハンドリングを実装することで、registration tokenの重複をふせぐことができるのではないか
[refresh tokenのハンドリング例](https://developers.google.com/instance-id/guides/android-implementation#refresh_tokens)

**Comment by hocnguyen** [comment]
About Instance ID, It will expired after 6 months.

> The Instance ID service initiates callbacks periodically (for example, every 6 months), requesting that your app refreshes its tokens. [>>Details ](https://developers.google.com/instance-id/guides/android-implementation#refresh_tokens)

Also  The InstanceID is long lived, but may expire for the following reasons:

- Device factory reset.
- User uninstalls the app.
- User performs “Clear Data” in the app.
- Device unused for an extended period (device and region determines the timespan).
- Instance ID service detects abuse or errors and resets the InstanceID.
- Server-side code if your client app requires that functionality.

Now, I see we had imported the library  to SDK: 
    ```  import com.google.android.gms.iid.InstanceID;  ```   _Line 10, NCMBInstallation.java_
Therefore, we can use refresh token and don't import anything into SDK again.

=> Conclude :  I think it is necessary to refresh token.

**Comment by ncmbadmin** [comment]
ハンドリング処理は現在実施していませんが、ＳＤＫ利用としては、アプリ起動するタイミングで、内部新デバイストークンを取得するように実施しているため、上記のケースはカバーできている状況です。

**Comment by ncmbadmin** [comment]
お世話になっております。
こちら回答済みのため、本issueをcloseさせていただきます。
今後とも、mobile backend をどうぞよろしくお願いいたします。
