### ISSUE TITLE
example プロジェクトが動作しない

### ISSUE THREAD

**Issue by bkzen** [NIFCLOUD-mbaas/ncmb_android#151]
## 不具合の概要(Description of bug)
最新の Android Studio で SDK 内の example プロジェクトが動作しません。

- SDKのバージョン(SDK version)
    - 2.3.2
- 不具合が発生した環境(Environment requirement)
    - 最新の Android Studio(3.0.1)
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
    - 最新の Android Studio でプロジェクトを開く
- エラーメッセージ(Error messages)
    - 例えば example/PushTest プロジェクトを開くと
```
Error Loading Project: Cannot load module ncmb-core
```
と表示されます。

**Comment by ncmbadmin** [comment]
v3.0.0対応時、exampleプロジェクトは削除済みのため、本issueは対応不要になりました
