### ISSUE TITLE
About the authenticationError

### ISSUE THREAD

**Issue by hahafather007** [NIFCloud-mbaas/ncmb_android#160]
This library in my Android project inited success,but when I used console to send push message,they were alwayes failed.

> {
    "android": {
        "total": 3,
        "authenticationError": 3
    },
    "description": {
        "status": "complete"
    }
}

And I saw this in google 

> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more. 

So what should I do?

**Comment by ncmbadmin** [comment]
Dear @hahafather007

Thank you for your posts and sorry for the late reply.
We have considered on your question.

It seems to be that you have some troubles about Push Notification system,
which is not directly concern to Android SDK.
We are sorry that we do not support about Push Notification usage here.

We suggest that you can post your question on the following User Community,
where free users can share their problems and get some hints from mbaas evangelist and other users.

https://github.com/NIFCloud-mbaas/UserCommunity/issues

Thanks and regards.
