### ISSUE TITLE
NCMB.initializeでinstallation登録される

### ISSUE THREAD

**Issue by nakagawa-yoshiki** [NIFCloud-mbaas/ncmb_android#182]
## SDKのバージョン(SDK version)
v3.0.1

## 事象 (Phenomenon)

※ monaca_push_plugin を利用しており、以下の現象が起こり調査していたところ、
  どうも、こちらのAndroid SDK側での挙動のようで対応できないか検討しています。

プッシュ通知を配信したくなくなったため、端末を installation から消しても、
NCMB.initialize 内にて、installationの登録処理を行われているようで、
アプリ再起動などで、NCMB.initializeすると、再度installationに登録されてしまいます。

https://github.com/NIFCloud-mbaas/ncmb_android/blob/82765036c0000799da58dc2d6fa637726b5fa8f4/ncmb-core/src/main/java/com/nifcloud/mbaas/core/NCMB.java#L205

以前のバージョン2系のSDKや、ncmb_ios ではこのような挙動とならないのですが、
Androidでも勝手に登録されないように戻すことはできますでしょうか？
※それとも現状のAndroidSDK側が正しく、自動登録されるのは仕様でしょうか？

## 確認手順

1. installationを登録する
2. installationを削除する
3. 再起動する。(NCMB.initializeを呼ぶ)
=> installationに登録される。

お手数おかけしますが、ご確認の程よろしくお願い致します。

**Comment by nakagawa-yoshiki** [comment]
こちらの件、その後、いかがでしょうか・・？

**Comment by ncmbsupport** [comment]
回答が遅くなってしまい申し訳ございません。

こちらの自動登録はFCM(Firebase Cloud Messaging)対応版からの仕様です。プッシュ機能を使用する設定をされている場合にのみ動作いたします。

今後も自動登録の仕様については変更する予定はございませんが、個々のケースにおいて自動登録を無効化する設定について可能かどうかの検討を進めてまいります。

**Comment by nakagawa-yoshiki** [comment]
@ncmbsupport ご回答ありがとうございます。
現状は仕様とのこと承知致しました。
今後の検討、何卒よろしくお願い致します。
