### ISSUE TITLE
AndroidXに更新

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/ncmb_android#204]
### 概要

現在内部Android SDKではAndroid Support Libraryを利用していますが、
以下のドキュメントにより、今後Android Support Libraryの更新はAndroidX（Android Support Libraryの後継）で行われ、AndroidXに移行を推奨しているため、本Android SDKも更新検討を行います。

```
 With the release of Android 9.0 (API level 28) there is a new version of the support library called AndroidX which is part of Jetpack. The AndroidX library contains the existing support library and also includes the latest Jetpack components. 
```
* 参照
https://developer.android.com/topic/libraries/support-library/packages

**Comment by kimpeng** [comment]
AndroidXに対応したバージョンはいつ頃リリースする予定でしょうか？

**Comment by ncmbadmin** [comment]
issueにコメントいただき、ありがとうございます。

AndroidX対応の検討を進めておりますが、具体的な対応時期に関してはまだ決まっておりません。
既存SDK利用からのアップデート時の影響調査も必要となりますので、対応完了まで時間を要しております。

なお、リリースされましたら、告知させていただきますので、
[informationブログ](https://mbaas.nifcloud.com/info/)にてご確認いただければと思います。
今後とも宜しくお願い致します。

**Comment by kimpeng** [comment]
ご回答ありがとうございます。
