### ISSUE TITLE
【メジャーアップデート】Android Studio 4.0への対応

### ISSUE THREAD

**Issue by kobayashi-masaya** [NIFCLOUD-mbaas/ncmb_android#216]
以下の動作確認及び手順変更の確認
・クイックスタート実施 + 手順、画像に問題がないか確認
・各プラットフォームのサンプル・チュートリアル + 手順、画像に問題がないか確認

**Comment by ncmbadmin** [comment]
・確認完了し、問題ないことを確認しました
・READMEを今後更新予定
issueとしてはクローズします
