### ISSUE TITLE
Travis CIからGithub Actionsへの移行(Android)

### ISSUE THREAD

**Issue by watanabe-tomoya** [NIFCLOUD-mbaas/ncmb_android#228]
他SDK同様、Travis CIからGithub Actionsへの移行を行う。
`.github/workflows`配下に`android.yml`を追加する。

**Comment by thuydg** [comment]
本件、以下のバージョンで対応完了したため、クローズします
v4.0.1
https://github.com/NIFCLOUD-mbaas/ncmb_android/pull/238
