### ISSUE TITLE
4系のAndroid端末でレスポンスの検証設定を有効にし、ファイル登録などを行うとエラーが発生する

### ISSUE THREAD

**Issue by n0guch1** [NIFCloud-mbaas/ncmb_android#73]
## 不具合の概要(Description of bug)
- SDKのバージョン(SDK version)
  - 2.2.3
- 不具合が発生した環境(Environment requirement)
  - Android - 4.2.2 （5.1.1では再現しない）
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
  - FileStoreSampleのPOSTボタンおよびGETボタンの処理を実施
- エラーメッセージ(Error messages)
  - Authentication error by respose signature incorrect.

**Comment by hocnguyen** [comment]
I tested on Android version 4.2.2 (API 17) . But I upload file and get content file success, no error .
My code : 
```
NCMBAcl acl = new NCMBAcl();
        acl.setPublicWriteAccess(true);
        acl.setPublicReadAccess(true);
        byte[] data = "Hello,NCMB".getBytes();
        NCMBFile file = new NCMBFile("Hello.txt", data,acl);
        file.saveInBackground(new DoneCallback() {
            @Override
            public void done(NCMBException e) {
                if (e != null) {
                    //失敗
                } else {
                    //成功
                }
            }
        });

NCMBFile file = new NCMBFile("Hello.txt");
        file.fetchInBackground(new FetchFileCallback() {
            @Override
            public void done(byte[] data, NCMBException e) {
                if (e != null) {
                    //失敗
                } else {
                    //成功
                }
            }
        });
```
Please help me confirm about that.

**Comment by ndyuya** [comment]
Did you enable the response validation?

```
NCMB.enableResponseValidation(true);
```

**Comment by hocnguyen** [comment]
@ndyuya さん
It has error when we enable the response validation.
But only POST method, Get method is no error.

**Comment by hocnguyen** [comment]
@ndyuya さん、
I see we have 2 result response data with Android 4.2.2 and 5.1.1
at responseSignatureCheck() of NCMBConnection file.
Android 4.2.2 : 

> {"createDate":"2016-12-13T07:03:21.574Z","fileName":"Hello.txt"}

Android 5.1.1 

> {"fileName":"Hello.txt","createDate":"2016-12-13T07:06:11.422Z"}

If we change format of return data response of Android 4.2.2 similar with Android 5.1.1.
 It is ok. No error.

**Comment by ndyuya** [comment]
```res.responseData``` in [NCMBConnection.java:L183](https://github.com/NIFTYCloud-mbaas/ncmb_android/blob/dc0dc12cdf46a4891516a4e13b2b4f5592e765ef/ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBConnection.java#L183) is JSONObject type that deserialized HTTP response body.
It is serialized again. ```res.responseData.toString ()``` at same line.
I think ,it(re-serialization) may be the cause ,not server response.

**Comment by hocnguyen** [comment]
yes. Now I see it return 2 results different when parse JSON at [NCMBResponse.java](https://github.com/NIFTYCloud-mbaas/ncmb_android/blob/dc0dc12cdf46a4891516a4e13b2b4f5592e765ef/ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBResponse.java#L59)
``` 
responseData = new JSONObject(new String(sb));
 ```
- Android 5.1.1 :  It is ok, keep position of key and value : 
{"fileName":"Hello.txt","createDate":"2016-12-13T07:06:11.422Z"}
- Android 4.2.2 :  It will be sort to : 
{"createDate":"2016-12-13T07:03:21.574Z","fileName":"Hello.txt"}

I think the cause from here.
