### ISSUE TITLE
Timeout Connection?

### ISSUE THREAD

**Issue by dovanvu1792** [NIFCLOUD-mbaas/ncmb_android#76]
How to set NCMBConnection sConnectionTimeout?

**Comment by ncmbadmin** [comment]
Thank you for your issue but we don't suggest post questions here, please use our [User Community](https://github.com/NIFCLOUD-mbaas/UserCommunity/blob/master/README_en.md) to ask questions about SDK and usages.

By the way, to set Connection timeout, we support the follow function
```
setTimeout()
```
Please see [SDK Reference](https://mbaas.nifcloud.com/assets/sdk_doc/android/javadoc/index.html) for details.
