### ISSUE TITLE
データストアから検索取得時、指定(LimitとSkip)の不具合

### ISSUE THREAD

**Issue by sensp** [NIFCloud-mbaas/ncmb_android#97]
## 不具合の概要(Description of bug)
-不：データストアからデータを検索時、query.count()後、ｌimit指定なしとlimit指定をすると１件しか取得しません。
-正：データストアからデータを検索時、query.count()後、limit指定なし(デフォルト=100件)とlimit指定が取得出来るようにする。

**Comment by sensp** [comment]
-再現条件：データストアからデータ1000件以上を準備
-ソースの例文
  NCMBQuery<NCMBObject> query = new NCMBQuery<>("MassDataClass");

   //query.setLimit(100); //設定無しのdefault=100を利用する
   query.setSkip(1000); //1000からdefault=100までのデータが取れるのが正解です。

    // データストアからデータを検索
    query.findInBackground(new FindCallback<NCMBObject>() {
        @Override
        public void done(List<NCMBObject> results, NCMBException e) {
            if (e != null) {

                //検索失敗時の処理
            } else {

                nowLogDate("取得 成功 count = " +  results.size());

                for(int i = 0 ; i < results.size(); i++) {
                    //検索成功時の処理
                    NCMBObject massCls = (NCMBObject) results.get(i);
                    Log.d("objectId=", massCls.getObjectId());
                    Log.d("no=", massCls.getString("no"));
                }

            }
        }
    });

**Comment by sensp** [comment]
try{

            //1.classデータが何件あるのかを取得
            NCMBQuery<NCMBObject> query = new NCMBQuery<>("MassDataClass");

            //2.データが何件あるのかを取得:総数　← ★これがあると下記のSKIP処理が邪魔している
            int iResult = query.count();
            Log.d("test","全取得 成功 count Size = " + iResult);

            //query.setLimit(1);
            query.setSkip(1000);

            //3.データが何件あるのかを取得(limite 1-1000)
            //query.setLimit(700);

            // データストアからデータを検索
            query.findInBackground(new FindCallback<NCMBObject>() {
                @Override
                public void done(List<NCMBObject> results, NCMBException e) {
                    if (e != null) {

                        //検索失敗時の処理
                    } else {

                        Log.d("test","SKIP取得 成功 count = " +  results.size());

                        for(int i = 0 ; i < results.size(); i++) {
                            //検索成功時の処理
                            NCMBObject massCls = (NCMBObject) results.get(i);
                            Log.d("objectId=", massCls.getObjectId());
                        }

                    }
                }
            });

        }catch (NCMBException error){
            error.printStackTrace();
        }

**Comment by sensp** [comment]
-再現条件：データストアからデータ1000件以上を準備
-例文
        try{
            //1.classデータが何件あるのかを取得
            NCMBQuery<NCMBObject> query = new NCMBQuery<>("MassDataClass");

            //2.データが何件あるのかを取得:総数　← ★これがあると下記のSKIP処理が邪魔している
            int iResult = query.count();
            Log.d("test","全取得 成功 count Size = " + iResult);

            //query.setLimit(1);
            query.setSkip(1000);

            //3.データが何件あるのかを取得(limite 1-1000)
            //query.setLimit(700);

            // データストアからデータを検索
            query.findInBackground(new FindCallback<NCMBObject>() {
                @Override
                public void done(List<NCMBObject> results, NCMBException e) {
                    if (e != null) {

                        //検索失敗時の処理
                    } else {

                        Log.d("test","SKIP取得 成功 count = " +  results.size());

                        for(int i = 0 ; i < results.size(); i++) {
                            //検索成功時の処理
                            NCMBObject massCls = (NCMBObject) results.get(i);
                            Log.d("objectId=", massCls.getObjectId());
                        }

                    }
                }
            });

        }catch (NCMBException error){
            error.printStackTrace();
        }
    }

**Comment by sensp** [comment]
-再現条件：データストアからデータ1000件以上を準備
-例文

        try{
            //1.classデータが何件あるのかを取得
            NCMBQuery<NCMBObject> query = new NCMBQuery<>("MassDataClass");

            //2.データが何件あるのかを取得:総数　← ★これがあると下記のSKIP処理が邪魔している
            int iResult = query.count();
            Log.d("test","全取得 成功 count Size = " + iResult);

            //query.setLimit(1);
            query.setSkip(1000);

            // データストアからデータを検索
            query.findInBackground(new FindCallback<NCMBObject>() {
                @Override
                public void done(List<NCMBObject> results, NCMBException e) {
                    if (e != null) {

                        //検索失敗時の処理
                    } else {

                        Log.d("test","SKIP取得 成功 count = " +  results.size());

                        for(int i = 0 ; i < results.size(); i++) {
                            //検索成功時の処理
                            NCMBObject massCls = (NCMBObject) results.get(i);
                            Log.d("objectId=", massCls.getObjectId());
                        }

                    }
                }
            });

        }catch (NCMBException error){
            error.printStackTrace();
        }
    }

**Comment by hocnguyen** [comment]
When we call : 

> int iResult = query.count();

 It always return 1 record. Because we set Skip 1000 records, So it always return 0 record.
I had investigated about that, From count() fucntion.
``` 
public int count () throws NCMBException {
              countFlag = true;
              limitNumber = 1;
              NCMBObjectService objServ = (NCMBObjectService)NCMB.factory(NCMB.ServiceType.OBJECT);
              return objServ.countObject(mClassName, getConditions());
    } 
```
 I think the reason because we set limitNumber variable is 1, so It always return result only 1 record.
I try remove **limitNumber = 1;** . It return the correct result .
Please help me confirm!
Thank you!

**Comment by ndyuya** [comment]
```limitNumber = 1;``` is a parameter to reduce the HTTP body of response.

```countFlag = true;``` and ```limitNumber = 1;``` are a temporary parameter used only during the processing of ```count ()``` or ```countInBackground()```.
But they are set as permanent parameters, they also affect the next query.

So I think we can fix it by saving ```countFlag``` and ```limitNumber``` before sending API request and restoring saved parameters after receiving API response.

**Comment by sensp** [comment]
下記の修正でプルリクエストを作成する。
場所：【com.nifty.cloud.mb.core.NCMBQuery.java】

-現在
<pre>
    public int count () throws NCMBException {
        countFlag = true;
        limitNumber = 1;
        NCMBObjectService objServ = (NCMBObjectService)NCMB.factory(NCMB.ServiceType.OBJECT);
        return objServ.countObject(mClassName, getConditions());
    }

    public void countInBackground(CountCallback callback) {
        countFlag = true;
        limitNumber = 1;
        NCMBObjectService objServ = (NCMBObjectService)NCMB.factory(NCMB.ServiceType.OBJECT);

        objServ.countObjectInBackground(mClassName, getConditions(), callback);
    }
</pre>
-修正
<pre>
    public int count () throws NCMBException {
        countFlag = true;
        limitNumber = 1;
        NCMBObjectService objServ = (NCMBObjectService)NCMB.factory(NCMB.ServiceType.OBJECT);

        //条件文の設定
        JSONObject countConditions = getConditions();
        //count用パラメータ初期化する
        limitNumber = 0;
        countFlag = false;
        return objServ.countObject(mClassName, countConditions);
    }

    public void countInBackground(CountCallback callback) {
        countFlag = true;
        limitNumber = 1;
        NCMBObjectService objServ = (NCMBObjectService)NCMB.factory(NCMB.ServiceType.OBJECT);

        //条件文の設定
        JSONObject countConditions = getConditions();
        //count用パラメータ初期化する
        limitNumber = 0;
        countFlag = false;
        objServ.countObjectInBackground(mClassName, countConditions, callback);
    }
</pre>
